name: Deploy na seohost (FTP)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wyslij pliki przez FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_PREZENTY }}
          password: ${{ secrets.FTP_PASSWORD_PREZENTY }}
          protocol: ftps
          server-dir: /home/srv71182/domains/prezenty.ovii.pl/
          exclude: |
            **/.git*
            **/.git*/**
            **/README.md
